spring.application.name=consumer
server.port=8082

# Core Connection
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=my-group-v2

# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Type Configuration Mapping Rules
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.consumer.kafka.event.TestEvent
