spring.application.name=producer

server.port=8081

# Connect to the local running Docker container
spring.kafka.bootstrap-servers=localhost:9092

# Configure JSON Serializer for handling objects
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

